---
title: "Análise exploratória - Tribunal de Justiça do Alagoas"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r setup, echo=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(tidy = FALSE, 
                      echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.height = 10,
                      fig.width = 8)
set.seed(1014)
options(digits = 2, scipen = 999, OutDec = ",")


Sys.setenv(LANGUAGE = "pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
```


```{r echo=FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(hrbrthemes)
library(ggbeeswarm)
library(lubridate)
library(here)

# peguei as cores do site e criei um vetor com nomes fáceis de lembrar
cores_dadosjusbr <- c(
  lilas = "#B361C6",
  cyan = "#2FBB96",
  cinza_azulado = "#3e5363",
  verde = "#96ba2f",
  laranja = "#F2C94C"
)

cores_natureza <- c(
  "Desconto" = cores_dadosjusbr[["lilas"]],
  "Recebimento" = cores_dadosjusbr[["cyan"]]
)

cores_indice <- c(
  "Transparência" = cores_dadosjusbr[["cyan"]],
  "Completude" = cores_dadosjusbr[["laranja"]],
  "Facilidade" = cores_dadosjusbr[["lilas"]]
  )

theme_set(
  theme_ipsum_rc() +
  theme(
    axis.ticks.x = element_line(),
    plot.title = element_text(color = cores_dadosjusbr[["cinza_azulado"]]),
    plot.subtitle = element_text(color = cores_dadosjusbr[["cinza_azulado"]]),
    axis.text.x = element_text(color = cores_dadosjusbr[["cinza_azulado"]]),
    axis.text.y = element_text(color = cores_dadosjusbr[["cinza_azulado"]]),
    axis.title.x = element_text(color = cores_dadosjusbr[["cinza_azulado"]]),
    axis.title.y = element_text(color = cores_dadosjusbr[["cinza_azulado"]]),
    legend.text = element_text(color = cores_dadosjusbr[["cinza_azulado"]]),
    legend.title = element_text(color = cores_dadosjusbr[["cinza_azulado"]]),
    strip.text = element_text(color = cores_dadosjusbr[["cinza_azulado"]])
  )
)

update_geom_font_defaults(color = cores_dadosjusbr[["cinza_azulado"]])
```


```{r}
estrutura <- function() {
  full <- cols(
    orgao = col_character(),
    receita_base = col_character(),
    despesas = col_character(),
    outras_receitas = col_character(),
    acesso = col_character(),
    ano = col_integer(),
    mes = col_integer(),
    acesso_i = col_integer(),
    indice_completude = col_double(), 
    indice_facilidade = col_double(),
    indice_transparencia = col_double(),
    tem_lotacao = col_logical(),
    tem_cargo = col_logical(),
    tem_matricula = col_logical(),
    nao_requer_login = col_logical(),
    nao_requer_captcha = col_logical(),
    formato_consistente = col_logical(),
    estritamente_tabular = col_logical()
  )
  media <- cols(
    orgao = col_character(),
    media_indice_completude = col_double(),
    media_indice_facilidade = col_double(),
    media_indice_transparencia = col_double()
  )
  
  return(list(full = full, media = media))
}

col_defs <- estrutura()

indice <- "data/load" %>% 
  here() %>%
  list.files(pattern = "^indice_transparencia.+",
             full.names = TRUE) %>% 
  set_names(c("full", "media")) %>% 
  map2(col_defs, ~ read_csv(.x, col_types = .y))
```

## Transparência nos tribunais de justiça

```{r}
indice$full %>% 
  filter(ano == 2020L) %>% 
  transmute(
    orgao = orgao %>% toupper() %>% str_replace("^TJ", "TJ-"),
    ano,
    indice_completude,
    indice_facilidade,
    indice_transparencia
  ) %>% 
  group_by(orgao, ano) %>% 
  summarise(across(starts_with("indice"), mean), .groups = "drop") %>% 
  pivot_longer(-c(orgao, ano), values_to = "pontuacao", names_to = "indice") %>%
  mutate(
    indice = case_when(
      indice == "indice_completude" ~ "Completude",
      indice == "indice_facilidade" ~ "Facilidade",
      TRUE ~ "Transparência"
  )) %>%
  ggplot(aes(
    y = reorder(orgao, pontuacao, sum),
    x = pontuacao
  )) +
  geom_line(color = cores_dadosjusbr[["cinza_azulado"]]) +
  geom_point(
    aes(fill = indice, size = indice),
    shape = 21) +
  scale_x_continuous(limits = c(0, 1)) +
  scale_size_manual(values = c("Completude" = 2.5, "Transparência" = 5, "Facilidade" = 2.5)) +
  scale_fill_manual(values = c(
    "Completude" = cores_dadosjusbr[["laranja"]],
    "Transparência" = cores_dadosjusbr[["cyan"]],
    "Facilidade" = cores_dadosjusbr[["lilas"]]
  )) +
  geom_curve(aes(x = .75, xend = 0.49, y = "TJ-RR", yend = "TJ-TO"),
             arrow = arrow(length = unit(2, "mm")), curvature = -0.5
             ) + 
  geom_label(
    aes(x = .8, y = "TJ-RR",
        label = str_glue("O índice de Transparência\né uma média das pontuações\n",
                         "obtidas nas dimensões\nCompletude e Facilidade")
        ),
    label.r = unit(0.3, "lines"),
    lineheight = 1.1
  ) +
  labs(
    title = "Índice de Transparência nos Tribunais de Justiça",
    subtitle = "Médias nos últimos 12 meses, por órgão",
    x = "Pontuação",
    y = NULL,
    fill = "Índice:",
    size = "Índice:"
  ) +
  theme(
    legend.position = "top",
    legend.justification = "left",
    legend.background = element_rect(fill = alpha(cores_dadosjusbr[["cinza_azulado"]], .1),
                                     color = "transparent")
  )
```

```{r}
indice$full %>% 
  transmute(
    orgao,
    ano,
    indice_completude,
    indice_facilidade,
    indice_transparencia
  ) %>% 
  group_by(orgao, ano) %>% 
  summarise(across(starts_with("indice"), mean), .groups = "drop") %>% 
  pivot_longer(-c(orgao, ano), names_to = "categoria", values_to = "pontuacao") %>% 
  filter(ano == 2020L) %>% 
  mutate(categoria = str_remove(categoria, "^indice_") %>% str_to_sentence() %>% str_replace("Transparencia", "Transparência"),
         categoria = ordered(categoria, levels = c("Completude", "Facilidade", "Transparência")),
         orgao = orgao %>% toupper() %>% str_replace("^TJ", "TJ-")) %>% 
  ggplot(aes(
    x = reorder(orgao, pontuacao),
    y = pontuacao,
    fill = categoria
  )) +
  geom_col(show.legend = F, alpha = .7) +
  geom_text(aes(label = round(pontuacao, 2)), hjust = 1, fontface = "bold", size = 4.5) +
  scale_y_continuous(limits = c(0, 1), expand = c(0, .01)) +
  scale_fill_manual(values = cores_indice) +
  coord_flip() +
  labs(
    title = str_glue("Transparência nos Tribunais de Justiça"),
    subtitle = "Médias para o ano de 2021",
    y = "Pontuação",
    x = "Órgão"
  ) +
  facet_wrap(~ categoria)
```

Gráficos separados:

```{r}
plot_indice_barra <- function(df, indice) {
  
  idx <- case_when(indice == "Transparência" ~ "indice_transparencia",
                   indice == "Completude" ~ "indice_completude",
                   indice == "Facilidade" ~  "indice_facilidade")
  
  df %>% 
    transmute(
      orgao,
      ano,
      indice_completude,
      indice_facilidade,
      indice_transparencia
    ) %>% 
    group_by(orgao, ano) %>% 
    summarise(across(starts_with("indice"), mean), .groups = "drop") %>% 
    pivot_longer(-c(orgao, ano), names_to = "categoria", values_to = "pontuacao") %>% 
    filter(ano == 2020L, categoria == idx) %>% 
    mutate(categoria = str_remove(categoria, "^indice_") %>% str_to_sentence(),
           orgao = orgao %>% toupper() %>% str_replace("^TJ", "TJ-")) %>% 
    ggplot(aes(
      x = reorder(orgao, pontuacao),
      y = pontuacao,
      fill = categoria
    )) +
    geom_col(show.legend = F, alpha = .7) +
    geom_text(aes(label = round(pontuacao, 2)), hjust = 1, fontface = "bold", size = 4.5) +
    scale_y_continuous(limits = c(0, 1), expand = c(0, .01)) +
    scale_fill_manual(values = cores_indice[[indice]]) +
    coord_flip() +
    labs(
      title = str_glue("Índice de {indice} nos Tribunais de Justiça"),
      subtitle = "Média para o ano de 2021",
      y = "Pontuação",
      x = "Órgão"
    )
  
}
```

```{r}
indice$full %>% 
  plot_indice_barra("Transparência")
```

```{r}
indice$full %>% 
  plot_indice_barra("Completude")
```

```{r}
indice$full %>% 
  plot_indice_barra("Facilidade")
```

## Valores registrados mês a mês

```{r fig.height=6, fig.width=10}

indice$full %>%
  transmute(
    orgao = orgao %>% toupper() %>% str_replace("^TJ", "TJ-"),
    data = dmy(str_glue("01-{mes}-{ano}")),
    indice_completude = indice_completude != 0,
    indice_facilidade = indice_facilidade != 0,
    indice_transparencia = indice_transparencia != 0
  ) %>%
  complete(orgao, data, fill = list(
    indice_completude = F,
    indice_facilidade = F,
    indice_transparencia = F
  )) %>% 
  mutate(
    mes = month.abb[month(data)],
    ano = year(data)
  ) %>% 
  # filter(orgao == "TJ-AL") %>% 
  ggplot(aes(
    x = data,
    y = reorder(orgao, indice_transparencia),
    fill = if_else(indice_transparencia, "0,65", "0") %>% 
      ordered(levels = c("0", "0,65"))
  )) +
  geom_tile(color = "gray90", size = .01) +
  scale_fill_manual(values = c("0" = cores_dadosjusbr[["cinza_azulado"]], 
                               "0,65" = cores_dadosjusbr[["cyan"]])) +
  scale_x_date(expand = c(0, 0)) +
  labs(
    title = "Índice de Transparência mês a mês",
    fill = "Pontuação\nno mês",
    x = "Cada célula representa 1 mês",
    y = NULL
  ) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.spacing = unit(2, "mm"),
        strip.text = element_text(face = "bold")) +
  facet_wrap(ano ~ ., nrow = 1, scales = "free_x", )
```

```{r fig.height=6, fig.width=10}

indice$full %>%
  transmute(
    orgao = orgao %>% toupper() %>% str_replace("^TJ", "TJ-"),
    data = dmy(str_glue("01-{mes}-{ano}")),
    indice_completude = indice_completude != 0,
    indice_facilidade = indice_facilidade != 0,
    indice_transparencia = indice_transparencia != 0
  ) %>%
  complete(orgao, data, fill = list(
    indice_completude = F,
    indice_facilidade = F,
    indice_transparencia = F
  )) %>% 
  mutate(
    mes = month.abb[month(data)],
    ano = year(data)
  ) %>% 
  # filter(orgao == "TJ-AL") %>% 
  ggplot(aes(
    x = data,
    y = reorder(orgao, indice_facilidade),
    fill = if_else(indice_facilidade, "0,8", "0") %>% 
      ordered(levels = c("0", "0,8"))
  )) +
  geom_tile(color = "gray90", size = .01) +
  scale_fill_manual(values = c("0" = cores_dadosjusbr[["cinza_azulado"]], 
                               "0,8" = cores_dadosjusbr[["lilas"]])) +
  scale_x_date(expand = c(0, 0)) +
  labs(
    title = "Índice de Facilidade mês a mês",
    fill = "Pontuação\nno mês",
    x = "Cada célula representa 1 mês",
    y = NULL
  ) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.spacing = unit(2, "mm"),
        strip.text = element_text(face = "bold")) +
  facet_wrap(ano ~ ., nrow = 1, scales = "free_x")
```

```{r fig.height=6, fig.width=10}

indice$full %>%
  transmute(
    orgao = orgao %>% toupper() %>% str_replace("^TJ", "TJ-"),
    data = dmy(str_glue("01-{mes}-{ano}")),
    indice_completude = indice_completude != 0,
    indice_facilidade = indice_facilidade != 0,
    indice_transparencia = indice_transparencia != 0
  ) %>%
  complete(orgao, data, fill = list(
    indice_completude = F,
    indice_facilidade = F,
    indice_transparencia = F
  )) %>% 
  mutate(
    mes = month.abb[month(data)],
    ano = year(data)
  ) %>% 
  # filter(orgao == "TJ-AL") %>% 
  ggplot(aes(
    x = data,
    y = reorder(orgao, indice_completude),
    fill = if_else(indice_completude, "0,5", "0") %>% 
      ordered(levels = c("0", "0,5"))
  )) +
  geom_tile(color = "gray80", size = .01) +
  scale_fill_manual(values = c("0" = cores_dadosjusbr[["cinza_azulado"]], 
                               "0,5" = cores_dadosjusbr[["laranja"]])) +
  scale_x_date(expand = c(0, 0)) +
  labs(
    title = "Índice de Completude mês a mês",
    fill = "Pontuação\nno mês",
    x = "Cada célula representa 1 mês",
    y = NULL
  ) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.spacing = unit(2, "mm"),
        strip.text = element_text(face = "bold")) +
  facet_wrap(ano ~ ., nrow = 1, scales = "free_x")
```
